import { PGlite } from '@electric-sql/pglite';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';

// Run the real migration and PL/pgSQL in embedded PostgreSQL; stub only Supabase-owned schemas.
const db = new PGlite();
await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
create schema auth; create table auth.users(id uuid primary key, raw_user_meta_data jsonb,email text,email_confirmed_at timestamptz);
create table auth.identities(id uuid primary key default gen_random_uuid(),user_id uuid references auth.users(id),provider text,identity_data jsonb);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth,public to authenticated,service_role; grant execute on function auth.uid() to authenticated;
create schema storage; create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);`);
await db.exec(await readFile(new URL('../supabase/migrations/202610040001_resq.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('../supabase/migrations/202610040002_resq_permissions.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('../supabase/migrations/202610040003_resq_owner.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('../supabase/migrations/20261004180820_resq_profile_avatars.sql',import.meta.url),'utf8'));
const legacyGoogle='00000000-0000-4000-8000-000000000020';
const customGoogle='00000000-0000-4000-8000-000000000021';
const identityGoogle='00000000-0000-4000-8000-000000000023';
await db.exec(`insert into auth.users(id,email,raw_user_meta_data) values('${legacyGoogle}','legacy@example.invalid','{"full_name":"Google Name","picture":"https://example.invalid/photo.png"}'),('${customGoogle}','custom@example.invalid','{"name":"Provider Name"}'),('${identityGoogle}','identity@example.invalid','{}');
insert into auth.identities(user_id,provider,identity_data) values('${identityGoogle}','google','{"name":"Identity Only","picture":"https://example.invalid/identity.png"}');
update profiles set display_name='Custom Name',avatar_key='tied-hair',avatar_color='amber',role='verifier' where id='${customGoogle}';`);
await db.exec(await readFile(new URL('../supabase/migrations/20261004181845_resq_google_profile_sync.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('../supabase/migrations/20261004233000_resq_avatar_system.sql',import.meta.url),'utf8'));
const premiumMigration = await readFile(new URL('../supabase/migrations/20261005004119_resq_premium_avatar_choices.sql',import.meta.url),'utf8');
await db.exec(premiumMigration);
await db.exec(premiumMigration); // Reapplying must preserve rows and constraints.
let checks=0;
function check(value,message){assert.ok(value,message);checks++;}
const legacy=(await db.query(`select * from profiles where id='${legacyGoogle}'`)).rows[0];
check(legacy.display_name==='Google Name' && legacy.avatar_url==='https://example.invalid/photo.png' && legacy.email==='legacy@example.invalid','Backfill copies Google name, photo and email');
const custom=(await db.query(`select * from profiles where id='${customGoogle}'`)).rows[0];
check(custom.display_name==='Custom Name' && custom.avatar_key==='tied-hair' && custom.avatar_color==='amber' && custom.role==='verifier','Backfill preserves customized profile and access');
check((await db.query(`select raw_user_meta_data->>'display_name' name from auth.users where id='${customGoogle}'`)).rows[0].name==='Custom Name','Existing customized name reaches Auth');
const identity=(await db.query(`select * from profiles where id='${identityGoogle}'`)).rows[0];
check(identity.display_name==='Identity Only' && identity.avatar_url==='https://example.invalid/identity.png','Backfill recovers metadata from Google identity');
const newGoogle='00000000-0000-4000-8000-000000000022';
await db.exec(`insert into auth.users(id,email,raw_user_meta_data) values('${newGoogle}','google@example.invalid','{"full_name":"New Google User","avatar_url":"https://example.invalid/avatar.png","role":"admin"}');`);
check((await db.query(`select display_name from profiles where id='${newGoogle}'`)).rows[0].display_name==='New Google User','New Google name is copied on signup');
check((await db.query(`select role from profiles where id='${newGoogle}'`)).rows[0].role==='pending','Google metadata never assigns access');
await db.exec(`update profiles set display_name='My Chosen Name',avatar_key='curly-hair',avatar_color='cyan' where id='${newGoogle}';`);
const customAuth=(await db.query(`select raw_user_meta_data m from auth.users where id='${newGoogle}'`)).rows[0].m;
check(customAuth.display_name==='My Chosen Name' && customAuth.avatar_key==='curly-hair' && customAuth.avatar_color==='cyan','Profile changes sync to Auth atomically');
await db.exec(`update auth.users set email='updated@example.invalid',raw_user_meta_data=raw_user_meta_data || '{"full_name":"Provider Changed","avatar_url":"https://example.invalid/updated.png"}' where id='${newGoogle}';`);
const returning=(await db.query(`select * from profiles where id='${newGoogle}'`)).rows[0];
check(returning.display_name==='My Chosen Name' && returning.avatar_key==='curly-hair' && returning.email==='updated@example.invalid' && returning.avatar_url==='https://example.invalid/updated.png','Returning sign-in refreshes provider details and preserves customization');
check((await db.query("select has_function_privilege('anon','resq_private.persist_profile_metadata()','EXECUTE') allowed")).rows[0].allowed===false,'Metadata trigger is not an exposed RPC');
check((await db.query("select has_function_privilege('anon','public.resq_role()','EXECUTE') allowed")).rows[0].allowed===false,'Anon cannot call role helper');
check((await db.query("select has_function_privilege('service_role','public.audit_created_record()','EXECUTE') allowed")).rows[0].allowed===false,'Trigger helper cannot be called by service API');
async function rejected(sql,code) { await assert.rejects(()=>db.exec(sql),e=>e.code===code);checks++; }
const rescuer='00000000-0000-4000-8000-000000000001';
const verifier='00000000-0000-4000-8000-000000000002';
const admin='00000000-0000-4000-8000-000000000003';
const pending='00000000-0000-4000-8000-000000000004';
await db.exec(`insert into auth.users(id,raw_user_meta_data) values('${rescuer}','{"display_name":"Rescuer","role":"admin"}'),('${verifier}','{}'),('${admin}','{}'),('${pending}','{}');`);
check((await db.query(`select avatar_key,avatar_color,avatar_shape,avatar_style from profiles where id='${rescuer}'`)).rows[0].avatar_key==='short-hair','New profiles receive the default avatar');
await db.exec(`set role service_role; update profiles set avatar_key='scout',avatar_color='emerald',avatar_shape='shield',avatar_style='3d' where id='${rescuer}'; reset role;`);
const updatedRescuer = (await db.query(`select avatar_key,avatar_color,avatar_shape,avatar_style from profiles where id='${rescuer}'`)).rows[0];
check(updatedRescuer.avatar_key==='scout','Server saves scout 3D Bitmoji avatar');
check(updatedRescuer.avatar_color==='emerald','Server saves emerald accent');
check(updatedRescuer.avatar_shape==='shield','Server saves shield avatar shape');
check(updatedRescuer.avatar_style==='3d','Server saves 3D avatar style');
for (const color of ['rose','indigo','lime','silver']) for (const shape of ['rounded-square','pentagon','star']) {
  await db.exec(`set role service_role; update profiles set avatar_color='${color}',avatar_shape='${shape}' where id='${rescuer}'; reset role;`);
  const saved = (await db.query(`select avatar_color,avatar_shape from profiles where id='${rescuer}'`)).rows[0];
  const metadata = (await db.query(`select raw_user_meta_data from auth.users where id='${rescuer}'`)).rows[0].raw_user_meta_data;
  check(saved.avatar_color===color && saved.avatar_shape===shape, 'New color and shape persist');
  check(metadata.avatar_color===color && metadata.avatar_shape===shape, 'New choices sync to profile metadata');
}
await rejected(`update profiles set avatar_key='untrusted-url' where id='${rescuer}'`,'23514');
await rejected(`update profiles set avatar_color='custom-code' where id='${rescuer}'`,'23514');
await rejected(`update profiles set avatar_shape='invalid-shape' where id='${rescuer}'`,'23514');
await rejected(`update profiles set avatar_style='4d' where id='${rescuer}'`,'23514');
check((await db.query(`select role from public.profiles where id='${rescuer}'`)).rows[0].role==='pending','Signup must ignore a client role');
await db.exec(`update profiles set role='rescuer' where id='${rescuer}'; update profiles set role='verifier' where id='${verifier}'; update profiles set role='admin' where id='${admin}';`);
const person=(await db.query(`insert into persons(name,consent_basis,created_by) values('Database test subject','research','${rescuer}') returning id`)).rows[0].id;
const match=(await db.query(`insert into matches(person_id,search_id,score,components,thresholds,created_by) values('${person}',gen_random_uuid(),0.9,'{}','{}','${rescuer}') returning id`)).rows[0].id;
check((await db.query('select count(*)::int n from audit_events')).rows[0].n===2,'Creation audit events');
await rejected(`select review_match('${match}','${rescuer}','verified','Independent evidence')`,'RQ403');
await rejected(`select review_match('${match}','${verifier}','verified',' ')`,'22023');
check((await db.query(`select status from matches where id='${match}'`)).rows[0].status==='pending','Rejected request must not change status');
await db.exec(`set role service_role; select review_match('${match}','${verifier}','verified','Independent evidence'); reset role;`);
check((await db.query(`select status from matches where id='${match}'`)).rows[0].status==='verified','Review commits state');
check((await db.query('select count(*)::int n from decisions')).rows[0].n===1,'Review commits one decision');
check((await db.query(`select count(*)::int n from audit_events where action='match.reviewed'`)).rows[0].n===1,'Review commits its audit');
await rejected(`select review_match('${match}','${verifier}','rejected','Different decision')`,'RQ409');
await rejected('delete from audit_events','RQ409');
await rejected(`update decisions set reason='Changed evidence'`,'RQ409');
await db.exec(`select assign_team_role('${pending}','${admin}','rescuer');`);
check((await db.query(`select role from profiles where id='${pending}'`)).rows[0].role==='rescuer','Admin approves pending account');
await rejected(`select assign_team_role('${verifier}','${rescuer}','rescuer')`,'RQ403');
await rejected(`select assign_team_role('${admin}','${admin}','pending')`,'RQ403');
await db.exec(`set role authenticated; set request.jwt.claim.sub='${rescuer}';`);
check((await db.query('select count(*)::int n from profiles')).rows[0].n===1,'Client sees only its own profile');
check((await db.query('select count(*)::int n from persons')).rows[0].n===1,'Approved member reads cases');
await rejected(`update profiles set role='admin'`,'42501');
await rejected(`update profiles set avatar_key='tied-hair'`,'42501');
await rejected('select embedding from reference_images','42501');
await rejected(`select review_match('${match}','${admin}','verified','Spoofed admin')`,'42501');
await db.exec(`reset role; update profiles set role='pending' where id='${pending}'; set role authenticated; set request.jwt.claim.sub='${pending}';`);
check((await db.query('select count(*)::int n from persons')).rows[0].n===0,'Pending account sees no cases');
check((await db.query('select count(*)::int n from matches')).rows[0].n===0,'Pending account sees no candidates');
await db.exec('reset role;');
check((await db.query(`select public from storage.buckets where id='case-photos'`)).rows[0].public===false,'Photo bucket must be private');
// Inject an audit failure: the transaction must roll back its match and decision writes.
const rollbackMatch=(await db.query(`insert into matches(person_id,search_id,score,components,thresholds,created_by) values('${person}',gen_random_uuid(),0.9,'{}','{}','${rescuer}') returning id`)).rows[0].id;
await db.exec(`create function fail_audit() returns trigger language plpgsql as $$begin raise exception 'Injected audit failure' using errcode='RQ500'; end$$; create trigger injected_failure before insert on audit_events for each row execute function fail_audit();`);
await rejected(`select review_match('${rollbackMatch}','${verifier}','rejected','Independent review')`,'RQ500');
check((await db.query(`select status from matches where id='${rollbackMatch}'`)).rows[0].status==='pending','Failed audit rolls back status');
check((await db.query(`select count(*)::int n from decisions where match_id='${rollbackMatch}'`)).rows[0].n===0,'Failed audit rolls back decision');
await db.exec('drop trigger injected_failure on audit_events;');
const owner='00000000-0000-4000-8000-000000000010';
const outsider='00000000-0000-4000-8000-000000000011';
await db.exec(`insert into auth.users(id,raw_user_meta_data,email) values('${owner}','{}','eswarch2004y@gmail.com');insert into auth.users(id,raw_user_meta_data,email,email_confirmed_at) values('${outsider}','{"role":"admin"}','outsider@example.invalid',now());`);
check((await db.query(`select role from profiles where id='${owner}'`)).rows[0].role==='pending','Owner must verify email first');
check((await db.query(`select role from profiles where id='${outsider}'`)).rows[0].role==='pending','Other verified email cannot bootstrap owner');
await db.exec(`update auth.users set email_confirmed_at=now() where id='${owner}';`);
check((await db.query(`select role from profiles where id='${owner}'`)).rows[0].role==='admin','Verified designated owner becomes admin');
check((await db.query(`select count(*)::int n from audit_events where action='owner.bootstrapped' and entity_id='${owner}'`)).rows[0].n===1,'Bootstrap records an audit event');
await db.exec(`update auth.users set email_confirmed_at=now() where id='${owner}';`);
check((await db.query(`select count(*)::int n from audit_events where action='owner.bootstrapped'`)).rows[0].n===1,'Owner bootstrap is consumed once');
await db.close();
console.log(JSON.stringify({postgresql_checks:checks,migration:'passed',rls:'passed',decision_transaction:'passed',scope:'Embedded PostgreSQL; real migration/functions with Supabase infrastructure schemas stubbed'}));
